# Generated by Django 5.1.6 on 2025-03-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creaated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='User',
            new_name='user',
        ),
    ]
